### ISSUE TITLE
 pip install -e . error 

### ISSUE THREAD

**Issue by igalvarez** [ansible/eda-server#295]
I'm getting this error:

(.venv) [eda@openshift eda-server]$ pip install -e .
Obtaining file:///home/eda/eda-server
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/eda/eda-server/.venv/bin/python /home/eda/eda-server/.venv/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpewhbaxxs
       cwd: /home/eda/eda-server
  Complete output (51 lines):
  Traceback (most recent call last):
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in __init__
      req = REQUIREMENT.parseString(requirement_string)
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
      raise exc
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
      loc, tokens = self._parse( instring, 0 )
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
      loc,tokens = self.parseImpl( instring, preloc, doActions )
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
      loc, exprtokens = e._parse( instring, loc, doActions )
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
      loc,tokens = self.parseImpl( instring, preloc, doActions )
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 3205, in parseImpl
      raise ParseException(instring, loc, self.errmsg, self)
  pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 4), (line:1, col:5)

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/eda/eda-server/.venv/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/eda/eda-server/.venv/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/eda/eda-server/.venv/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 163, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 18, in <module>
      setup()
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/setuptools/__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in _install_setup_requires
      dist.parse_config_files(ignore_option_errors=True)
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/setuptools/dist.py", line 807, in parse_config_files
      self._finalize_requires()
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/setuptools/dist.py", line 534, in _finalize_requires
      self._move_install_requirements_markers()
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/setuptools/dist.py", line 573, in _move_install_requirements_markers
      inst_reqs = list(pkg_resources.parse_requirements(spec_inst_reqs))
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3099, in parse_requirements
      yield Requirement(line)
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3109, in __init__
      super(Requirement, self).__init__(requirement_string)
    File "/tmp/pip-build-env-ek5kobu2/overlay/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 105, in __init__
      f'Parse error at "{ requirement_string[e.loc : e.loc + 8]!r}": {e.msg}'
  pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "':require'": Expected stringEnd
  ----------------------------------------
WARNING: Discarding file:///home/eda/eda-server. Command errored out with exit status 1: /home/eda/eda-server/.venv/bin/python /home/eda/eda-server/.venv/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpewhbaxxs Check the logs for full command output.
ERROR: Command errored out with exit status 1: /home/eda/eda-server/.venv/bin/python /home/eda/eda-server/.venv/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpewhbaxxs Check the logs for full command output.
(.venv) [eda@openshift eda-server]$ pip list
Package    Version
---------- -------
pip        21.3.1
setuptools 39.2.0

Pls, help me to fix it.
Thxxxx

**Comment by cutwater** [comment]
It looks like you have too old `setuptools` version. Try updating it.
